version: '3'

tasks:
  default:
    cmds:
      - task -l

  preview:
    desc: preview
    cmds:
      - npx zenn preview

  article:
    desc: create new article
    cmds:
      - npx zenn new:article

  lint:
    desc: create new article
    cmds:
      - npx textlint articles
